### PR TITLE
Added mysevermanager.com rss instance

### PR DESCRIPTION
**Pull request by vdbhb59**
Added mysevermanager.com rss instance. This needs invite which can be done by mailing to hostmaster@myservermanager.com. More details on the service page: https://myservermanager.com/services/rss.html

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Cool

**Comment by vdbhb59** [comment]
If okay, kindly merge this one. :)

**Comment by Frenzie** [comment]
@Alkarex?

**Comment by Alkarex** [comment]
Thanks!
There was a `<div>` too much, fixed. Re-ordered alphabetically.

**Comment by v4rakh** [comment]
@vdbhb59 @Alkarex I am the maintainer of that service. I'd like to kindly ask to remove the page again, I am getting a lot of new requests since you've put my service on that page.

**Comment by vdbhb59** [comment]
Sure. I need to remove my service too @Alkarex as recently I had a database breach and now my service provider has limited the system resources too much. I will make the changes in few days once I am free.

**Comment by Alkarex** [comment]
Done https://github.com/FreshRSS/freshrss.org/commit/17c00c1823248937e6c05d41895b0d522d42765e

**Comment by math-GH** [comment]
@vdbhb59 I want to highlight that FreshRSS supports a custom TOS (Terms of Service) page:

grafik

https://freshrss.github.io/FreshRSS/en/admins/12_User_management.html#enable-terms-of-service-tos

**Comment by vdbhb59** [comment]
@math-GH yes, I know and I had it as well. You must recall our discussions on it. But not sure what is the relevance now as I had to take offline everything. The instance is no longer available.

**Pull request merged**
