### PR TITLE
Added my feed instance to the providers list

### PR DESCRIPTION
**Pull request by vdbhb59**
Added "https://feeds.flossboxin.org.in", my FLOSS Feeds to the list of providers, as I have opened my instance to the public for registrations. Hope to get it added to the list. :)
If I made any mistakes in the form filling, please let me know (instead of rejecting), and I will correct it. vdbhb59/FLOSSbOxIN

### CODE REVIEW

**Comment by Alkarex** [comment]
Hello and thanks for the instance,
It would be nice with a landing page with a few words describing your instance, maybe with some kind of contact information as well

**Comment by math-GH** [comment]
You can enable the TOS (Terms of Service) too and use it to describe your service.

How to enable: https://freshrss.github.io/FreshRSS/en/admins/12_User_management.html#enable-terms-of-service-tos

**Comment by Alkarex** [comment]
@vdbhb59 Please let us know when you have a little description of your instance.

A technical note: I can see you are exposing the `/p/` in the URL. Although that works, it is not optimal.

* https://freshrss.github.io/FreshRSS/en/admins/03_Installation.html
* https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html
* https://freshrss.github.io/FreshRSS/en/users/07_Frequently_Asked_Questions.html#what-is-i-at-the-end-of-the-application-url

After fixing it, make sure to check your `base_url` in `./FreshRSS/data/config.php`

Alternatively, using our Official Docker image takes care of those issues, among others, and is production-ready:

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md

**Comment by vdbhb59** [comment]
I have done the TOS. or the trailing /p, since I have this instance on shared hosting, I do not have an option for any apache/nginx changes to be made. I do not have root access and most things are permission denied, so it will not happen.

Can this PR be merged?

**Comment by Alkarex** [comment]
@math-GH Aren't we supposed to see the ToS on the login page, when enabled?
I cannot see them on https://feeds.flossboxin.org.in

**Comment by vdbhb59** [comment]
> @math-GH Aren't we supposed to see the ToS on the login page, when enabled? I cannot see them on https://feeds.flossboxin.org.in

Agreed. I am trying to understand it myself, why it does not show, even though I added it as per the steps. I wrote things there myself, which is bare minimum, for the sake of a TOS, which is not forced, afaiu.

**Comment by math-GH** [comment]
Is the current `edge` (1.21.1-dev) or the stable 1.21.0 installed?
Is the `tos.html` file in `\data` available (I do not mean `tos.example.html`?

**Comment by vdbhb59** [comment]
> Is the current `edge` (1.21.1-dev) or the stable 1.21.0 installed? Is the `tos.html` file in `\data` available (I do not mean `tos.example.html`?

Stable 12.1.0, and the tos.html is present in the \data folder.

image
image

**Comment by math-GH** [comment]
OK, the link to the TOS will be visible on the login screen with the next release (see PR https://github.com/FreshRSS/FreshRSS/pull/5222, merged into `edge` branch)

**Comment by math-GH** [comment]
To switch to the current `edge` branch you need to change from `'environment' => 'development',` to `development` in `data\config.php`

**Comment by vdbhb59** [comment]
> To switch to the current `edge` branch you need to change from `'environment' => 'production',` to `development` in `data\config.php`

Thanks, but I still get blast no update available. I changed from 'production' to 'development' there.

**Comment by math-GH** [comment]
Is the `.git` folder in your installation? Do you have Git available on your machine?

**Comment by vdbhb59** [comment]
> Is the `.git` folder in your installation? Do you have Git available on your machine?

Ohh nope. I remember, installed it via softaculous initially back in October 2022, and since then the instance updates automatically for stable branches or I update via update check.
If the new stable is going to come soon, in this month or maybe latest by next month 1st week, I can stick with 1.21.0 until then.
:)

**Pull request merged**
